export const musics = [
  {
    id: 1,
    name: "Thôi anh không chơi",
    srcAudio: "/audio/ThoiAnhKhongChoi.mp3",
    artistID: 1,
    count: 0,
    srcImg: "/imgs/song-1.jpeg",
    albumID: 3,
  },
  {
    id: 2,
    name: "Day by day",
    srcAudio: "/audio/HaruHaru.mp3",
    artistID: 2,
    count: 0,
    srcImg: "/imgs/song-2.jpeg",
    albumID: 2,
  },
  {
    id: 3,
    name: "Blue",
    srcAudio: "/audio/Blue.mp3",
    artistID: 3,
    count: 0,
    srcImg: "/imgs/song-3.jpeg",
    albumID: 2,
  },
  {
    id: 4,
    name: "Loser",
    srcAudio: "/audio/Loser.mp3",
    artistID: 2,
    count: 0,
    srcImg: "/imgs/song-1.jpeg",
    albumID: 2,
  },
  {
    id: 5,
    name: "Tình bạn diệu kỳ",
    srcAudio: "/audio/TinhBanDieuKy.mp3",
    artistID: 1,
    count: 0,
    srcImg: "/imgs/song-2.jpeg",
    albumID: 6,
  },
  {
    id: 6,
    name: "So in love",
    srcAudio: "/audio/SoInLove.mp3",
    artistID: 3,
    count: 0,
    srcImg: "/imgs/song-3.jpeg",
    albumID: 3,
  },
  {
    id: 7,
    name: "Xuân yêu thương",
    srcAudio: "/audio/XuanYeuThuong.mp3",
    artistID: 2,
    count: 0,
    srcImg: "/imgs/song-1.jpeg",
    albumID: 2,
  },
  {
    id: 8,
    name: "Happy New Year",
    srcAudio: "/audio/HappyNewYear.mp3",
    artistID: 1,
    count: 0,
    srcImg: "/imgs/song-2.jpeg",
    albumID: 2,
  },
]
